# 1
FROM ubuntu:latest

# 2 & 3
RUN apt-get update && apt-get upgrade
RUN apt-get install nginx

# 4
ADD ./lab/static/index.html /home/app/

# 5 & 6
COPY ./lab/ /home/lab/
RUN pip install pandas

# 7
RUN python manage.py migrate
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# 8
FROM nginx:alpine
FROM python:3.11
