services:
  web:
    image: nginx
    container_name: web
    networks:
      - web_network
  
  db:
    image: redis
    container_name: db
    networks:
      - db_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge