# 1
FROM ubuntu:22.04

# 2 & 3
RUN apt-get update && apt-get install nginx

# 4
COPY ./lab/static/index.html /home/lab/

# 5 & 6
COPY ./lab/requirements.txt /home/lab/requirements.txt
WORKDIR /home/lab/
RUN pip install -r requirements.txt
COPY ./lab/ /home/lab/

# 7
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# 8
FROM python:3.11
